<?php

/**
 * ALTAS_BAJAS_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ALTAS_BAJAS_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ALTAS_BAJAS_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ALTAS_BAJAS_VW');
    }
}