<?php

/**
 * CMB_ANNO_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CMB_ANNO_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CMB_ANNO_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CMB_ANNO_MVW');
    }
}