<?php

/**
 * COBERTURAS_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class COBERTURAS_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object COBERTURAS_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('COBERTURAS_MVW');
    }
}