<?php

/**
 * CONTRATO_POLIZA_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CONTRATO_POLIZA_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CONTRATO_POLIZA_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CONTRATO_POLIZA_VW');
    }
}