<?php

/**
 * DISPONIBILIDAD_FONDO_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DISPONIBILIDAD_FONDO_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DISPONIBILIDAD_FONDO_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DISPONIBILIDAD_FONDO_MVW');
    }
}