<?php

/**
 * DISPONIBILIDAD_FONDO_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DISPONIBILIDAD_FONDO_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DISPONIBILIDAD_FONDO_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DISPONIBILIDAD_FONDO_VW');
    }
}