<?php

/**
 * ENTE_CONTRATANTE_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ENTE_CONTRATANTE_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ENTE_CONTRATANTE_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ENTE_CONTRATANTE_VW');
    }
}