<?php

/**
 * EVOLUCION_POR_MESTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EVOLUCION_POR_MESTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EVOLUCION_POR_MESTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EVOLUCION_POR_MES');
    }
}