<?php

/**
 * FONDO_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FONDO_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FONDO_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FONDO_MVW');
    }
}