<?php

/**
 * PARENTESCO_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PARENTESCO_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PARENTESCO_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PARENTESCO_VW');
    }
}