<?php

/**
 * POBLACION_CONSOLIDADA_LISTA_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POBLACION_CONSOLIDADA_LISTA_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POBLACION_CONSOLIDADA_LISTA_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POBLACION_CONSOLIDADA_LISTA_VW');
    }
}