<?php

/**
 * POBLACION_RAN_EDA_SEX_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POBLACION_RAN_EDA_SEX_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POBLACION_RAN_EDA_SEX_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POBLACION_RAN_EDA_SEX_MVW');
    }
}