<?php

/**
 * POBLACION_EVOLUCION_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POBLACION_EVOLUCION_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POBLACION_EVOLUCION_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POBLACION_EVOLUCION_VW');
    }
    
    public static function getListaPoblacionEvolucion()
    {
        //return Doctrine_Core::getTable('POBLACION_EVOLUCION_VW');
        
        $q = $this->createQuery('j')
            ->where('CENTRO_COSTO = ?', $var_CentroCosto )
            ->andWhere('IDEPOL = ?', $var_IdPol)
            ->andWhere('anno = ?', $var_anno)
            ->andWhere('codparent = ?', $var_codparent)
                
            ;
        
    }
    
    
    
    
}