<?php

/**
 * POBLACION_EVOLUCION_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POBLACION_EVOLUCION_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POBLACION_EVOLUCION_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POBLACION_EVOLUCION_MVW');
    }
}