<?php

/**
 * POBLACION_CONSOLIDADA_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POBLACION_CONSOLIDADA_VWTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object POBLACION_CONSOLIDADA_VWTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('POBLACION_CONSOLIDADA_VW');
    }

    public static function getPoblacionConsolidada($varBusq) {
        $q = Doctrine_Query::create()
                ->from('POBLACION_CONSOLIDADA_VW  J')
                ->where('CODPARENT = ?', $varBusq);

        return $this->POBLACION_CONSOLIDADA_VW = $q->execute();
        
        
        
    }

}