<?php

/**
 * PR_CONSULTA_FONDOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PR_CONSULTA_FONDOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PR_CONSULTA_FONDOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PR_CONSULTA_FONDO');
    }
}