<?php

/**
 * PRUEBA_PROCEDURETable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PRUEBA_PROCEDURETable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PRUEBA_PROCEDURETable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PRUEBA_PROCEDURE');
    }
}