<?php

/**
 * R_CLIENTE_USUARIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class R_CLIENTE_USUARIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object R_CLIENTE_USUARIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('R_CLIENTE_USUARIO');
    }
}