<?php

/**
 * R_CLIENTE_USUARIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    autoservicio
 * @subpackage model
 * @author     Marvin Baptista
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class R_CLIENTE_USUARIO extends BaseR_CLIENTE_USUARIO
{

}