<?php

/**
 * SF_GUARD_GROUPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SF_GUARD_GROUPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SF_GUARD_GROUPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SF_GUARD_GROUP');
    }
}