<?php

/**
 * SF_GUARD_USER_PERMISSION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    autoservicio
 * @subpackage model
 * @author     Marvin Baptista
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SF_GUARD_USER_PERMISSION extends BaseSF_GUARD_USER_PERMISSION
{

}