<?php

/**
 * SF_GUARD_USERTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SF_GUARD_USERTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SF_GUARD_USERTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SF_GUARD_USER');
    }
}