<?php

/**
 * SF_GUARD_FORGOT_PASSWORDTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SF_GUARD_FORGOT_PASSWORDTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SF_GUARD_FORGOT_PASSWORDTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SF_GUARD_FORGOT_PASSWORD');
    }
}