<?php

/**
 * SINIESTRALIDAD_VWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SINIESTRALIDAD_VWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SINIESTRALIDAD_VWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SINIESTRALIDAD_VW');
    }
}