<?php

/**
 * SINIESTRALIDAD_MVWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SINIESTRALIDAD_MVWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SINIESTRALIDAD_MVWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SINIESTRALIDAD_MVW');
    }
}