# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security
# Activar o desactivar session de validacion de usuarios

default:
  is_secure: true

