# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
# autoservicio

default:
  http_metas:
    content-type: text/html; charset=UTF8

  metas:
    title:        Autoservicio Contratante - HMO SERVISALUD
    description:  Sistema de autoservicio contratante - HMO SERVISALUD
    keywords:     HMOSERVISALUD, HMO, Autoservicio
    language:     es
    #robots:       index, follow

  stylesheets:    [genericStyles.css,digg.css]

  javascripts:    [jquery-1.6.min.js, jquery.jCombo.min.js,jquery.mCombo.js, jquery.PrintArea.js, autoservicioPrintArea.js, jquery.dataTables.js, dias_habiles.js, jsapi.js]
  has_layout:     true
  layout:         layout
